# Generated by Django 5.2.1 on 2025-08-02 13:18

import django.db.models.deletion
import django.utils.timezone
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedCompanies',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(max_length=255, verbose_name='abbreviation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=utils.utils.company_logo_path, verbose_name='logo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Listed Companies',
                'verbose_name_plural': 'Listed Companies',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrices',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('opening_price', models.IntegerField(blank=True, null=True)),
                ('closing_price', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shares.listedcompanies')),
            ],
            options={
                'verbose_name': 'Historical Prices',
                'verbose_name_plural': 'Historical Prices',
            },
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('number_of_shares', models.IntegerField(blank=True, default=0, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shares.listedcompanies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Share Holdings',
                'verbose_name_plural': 'Share Holdings',
            },
        ),
        migrations.CreateModel(
            name='PortfolioLots',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('number_of_shares', models.IntegerField(blank=True, default=0, null=True)),
                ('purchased_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shares.portfolios')),
            ],
            options={
                'verbose_name': 'Share Holdings',
                'verbose_name_plural': 'Share Holdings',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('number_of_shares', models.IntegerField(blank=True, null=True)),
                ('transacted_price', models.FloatField(blank=True, null=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shares.listedcompanies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='WishLists',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shares.listedcompanies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wish Lists',
                'verbose_name_plural': 'Wish Lists',
            },
        ),
    ]
