# Generated by Django 5.0.7 on 2025-08-27 16:52

import django.utils.timezone
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'FAQs',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
