# Generated by Django 5.2.1 on 2025-07-26 18:03

import django.db.models.deletion
import django.utils.timezone
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('number_of_shares', models.IntegerField(blank=True, null=True)),
                ('transacted_price', models.FloatField(blank=True, null=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('transaction_type', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shares.listedcompanies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
