# Generated by Django 5.0.7 on 2025-09-23 12:57

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0004_stockmarketdata_delete_historicalprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepseIndices',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('index_value', models.CharField(max_length=255)),
                ('absolute_change', models.CharField(max_length=255)),
                ('percentage_change', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NepseIndices',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='listedcompanies',
            name='sector',
            field=models.CharField(default='', max_length=255, verbose_name='sector'),
        ),
    ]
