# Generated by Django 5.2.17 on 2026-09-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0005_nepseindices_listedcompanies_sector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NepseIndices',
        ),
        migrations.DeleteModel(
            name='StockMarketData',
        ),
    ]
