# Generated by Django 5.2.17 on 2026-09-19 12:50

import django.db.models.deletion
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0006_delete_nepseindices_delete_stockmarketdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarketData',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('day_average_120', models.CharField(max_length=255)),
                ('day_average_180', models.CharField(max_length=255)),
                ('day_average_volume_30', models.CharField(max_length=255)),
                ('year_yield_1', models.CharField(max_length=255)),
                ('weeks_high_low_52', models.CharField(max_length=255)),
                ('book_value', models.CharField(max_length=255)),
                ('eps', models.CharField(max_length=255)),
                ('last_traded_date', models.CharField(max_length=255)),
                ('market_capitalization', models.CharField(max_length=255)),
                ('market_price', models.CharField(max_length=255)),
                ('p_e_ratio', models.CharField(max_length=255)),
                ('pbv', models.CharField(max_length=255)),
                ('percent_bonus', models.CharField(max_length=255)),
                ('percent_change', models.CharField(max_length=255)),
                ('percent_dividend', models.CharField(max_length=255)),
                ('right_share', models.CharField(max_length=255)),
                ('shares_outstanding', models.CharField(max_length=255)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shares.listedcompanies')),
            ],
            options={
                'verbose_name': 'Stock Market Data',
                'verbose_name_plural': 'Stock Market Data',
            },
        ),
    ]
