# Generated by Django 5.2.17 on 2026-09-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0007_stockmarketdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMarketData',
        ),
    ]
