# Generated by Django 5.2.1 on 2025-08-08 13:49

import django.db.models.deletion
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('low_target', models.FloatField(blank=True, null=True)),
                ('high_target', models.FloatField(blank=True, null=True)),
                ('target_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=50, verbose_name='target type')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shares.listedcompanies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Targets',
                'verbose_name_plural': 'Targets',
            },
        ),
    ]
