# Generated by Django 5.2.1 on 2025-06-06 17:00

import django.db.models.deletion
import django.utils.timezone
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivities',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('activity', models.TextField(editable=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
