# Generated by Django 5.2.1 on 2025-08-10 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='targets',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='targets',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates whether the target is deleted or not.', verbose_name='is deleted'),
        ),
        migrations.AddField(
            model_name='targets',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated at'),
        ),
    ]
