# Generated by Django 5.0.7 on 2025-08-27 16:00

import django.db.models.deletion
import django.utils.timezone
import utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_targets_created_at_targets_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testonomials',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testonomials',
                'verbose_name_plural': 'Testonomials',
            },
        ),
    ]
