# Generated by Django 4.2.4 on 2026-01-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0006_targets_uniq_active_target_per_user_company_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targets",
            name="created_at",
            field=models.DateTimeField(auto_now=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="targets",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
