# Generated by Django 5.0.7 on 2025-10-25 12:21

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_testonomials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', max_length=255, null=True, upload_to=utils.utils.user_profile_path, verbose_name='profile image'),
        ),
    ]
