# Generated by Django 4.2.4 on 2026-01-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="targets",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user_id", "company_id", "target_type"),
                name="uniq_active_target_per_user_company_type",
            ),
        ),
    ]
