# Generated by Django 4.2.4 on 2026-01-13 08:48

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0007_alter_targets_created_at_alter_targets_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=utils.utils.generate_uuid_hex,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "FeedBack",
            },
        ),
    ]
