# Generated by Django 5.0.7 on 2025-08-28 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0002_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolios',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
    ]
