# Generated by Django 5.0.7 on 2025-09-14 14:18

import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shares', '0003_portfolios_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarketData',
            fields=[
                ('id', models.CharField(default=utils.utils.generate_uuid_hex, max_length=255, primary_key=True, serialize=False)),
                ('trade_date', models.DateField()),
                ('ltp', models.CharField(max_length=255)),
                ('pct_change', models.CharField(max_length=255)),
                ('high', models.CharField(max_length=255)),
                ('low', models.CharField(max_length=255)),
                ('open_price', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
                ('turnover', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MarketData',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='HistoricalPrices',
        ),
    ]
