# Generated by Django 4.2.4 on 2026-01-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Shares", "0005_nepseindices_listedcompanies_sector"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PortfolioLots",
        ),
    ]
